import type { AppConfig } from './app-config';

/**
 * Compiled fallback configuration.
 *
 * This is the ONLY place in `src/app` where tunable literals may live, and it
 * exists so the app degrades gracefully instead of white-screening when
 * `/assets/config/app-config.json` is missing or malformed (e.g. a bad deploy).
 * Every value here must mirror `public/assets/config/app-config.json`.
 *
 * Changing behavior = editing the JSON, never this file.
 * Allowlisted in tools/hardcode-allowlist.txt.
 */
export const DEFAULT_APP_CONFIG: AppConfig = {
  site: {
    url: 'https://feasly.com',
    name: 'Feasly',
  },
  api: {
    baseUrl: '',
    useMockApi: true,
    timeoutMs: 15000,
  },
  features: {
    sampleReport: true,
    renovationWaitlist: false,
  },
  wizard: {
    sqftDefault: 2200,
    sqftMin: 800,
    sqftMax: 6000,
  },
  timings: {
    debounceMs: 300,
    resendCooldownSec: 60,
    mockLatencyMinMs: 400,
    mockLatencyMaxMs: 900,
  },
  limits: {
    communityPageLimit: 24,
  },
  analytics: {
    enabled: false,
    optInWording: 'Allow anonymous usage analytics to help improve Feasly.',
  },
  copy: {
    tagline: 'Know what your infill build will cost — before you commit.',
    narrativeDisclaimer:
      'Dollar figures are calculated deterministically from our cost model — not generated by AI.',
  },
};
