import type { AppConfig } from './app-config';

/**
 * Compiled fallback configuration.
 *
 * This is the ONLY place in `src/app` where tunable literals may live, and it
 * exists so the app degrades gracefully instead of white-screening when
 * `/assets/config/app-config.json` is missing or malformed (e.g. a bad deploy).
 * Every value here must mirror `public/assets/config/app-config.json`,
 * EXCEPT `site.url`: the JSON ships `""` ("use the request origin at runtime")
 * while this file keeps the `https://feasly.com` placeholder so prerendered
 * HTML still emits absolute tags. See `apps/web/SEO.md` for the SITE_URL story.
 *
 * Changing behavior = editing the JSON, never this file.
 * Allowlisted in tools/hardcode-allowlist.txt.
 */
export const DEFAULT_APP_CONFIG: AppConfig = {
  site: {
    // PLACEHOLDER — the production domain is undecided (feasly.com unverified).
    // Prerender fallback only: at runtime the JSON's "" wins and SeoService
    // uses the request origin. Swap when Karan confirms the domain (SEO.md).
    url: 'https://feasly.com',
    name: 'Feasly',
    socialImage: '/assets/og/og-default.png',
  },
  api: {
    baseUrl: '',
    useMockApi: true,
    timeoutMs: 15000,
  },
  propertyData: {
    source: 'live',
    baseUrl: 'https://data.calgary.ca',
    datasetId: '4bsw-nn7w',
    searchRowLimit: 50,
    cacheTtlMs: 300000,
  },
  features: {
    // Q4 unconfirmed (Karan): the slot renders only when this is true AND a
    // sample report route exists — never a dead link.
    sampleReport: false,
    renovationWaitlist: false,
  },
  wizard: {
    sqftDefault: 2200,
    sqftMin: 1200,
    sqftMax: 4000,
    sqftStep: 50,
    renoSqftDefault: 800,
    renoSqftMin: 200,
    renoSqftMax: 3000,
    renoSqftStep: 50,
    renoAdditionCap: 400,
  },
  timings: {
    debounceMs: 250,
    reviseDebounceMs: 400,
    resendCooldownSec: 60,
    mockLatencyMinMs: 400,
    mockLatencyMaxMs: 900,
  },
  limits: {
    communityPageLimit: 24,
    autocompleteSuggestionLimit: 6,
  },
  analytics: {
    enabled: false,
    optInWording: 'Allow anonymous usage analytics to help improve Feasly.',
  },
  copy: {
    tagline: 'Know what your infill build will cost — before you commit.',
    narrativeDisclaimer:
      'Dollar figures are calculated deterministically from our cost model — not generated by AI.',
    landing: {
      eyebrow: 'Calgary Custom Infill · Free Feasibility Estimates',
      heroTitle: 'What will it really cost to build your home in Calgary?',
      heroSub:
        'A free range-based estimate for your Calgary infill project — land, build, and total investment — in under 2 minutes.',
      seoDescription:
        'Feasly estimates what it really costs to build a home in Calgary, Alberta — based on City property records and current construction cost data.',
      trustItems: ['Range-based estimates', 'Real City of Calgary data', 'AI cost breakdown'],
      trustItemsMock: [
        'Range-based estimates',
        'Sample property data — live City records coming soon',
        'AI cost breakdown',
      ],
      howItWorksTitle: 'Estimate in 2 minutes',
      howItWorksSub: 'No registration required. No phone calls. No salesperson involved.',
      steps: [
        {
          n: '01',
          title: 'Enter your Calgary address',
          body: 'We pull the City property record — lot size, zoning, and assessed value.',
        },
        {
          n: '02',
          title: 'Configure your scope',
          body: 'Square footage, finish tier, garage, and basement. Approximate figures are fine.',
        },
        {
          n: '03',
          title: 'Unlock your full report',
          body: 'A range-based estimate with an AI summary, risk factors, and a downloadable PDF.',
        },
      ],
      sampleReportLabel: 'See a sample report →',
    },
    search: {
      label: 'Your Calgary address',
      placeholder: 'Start typing your street address…',
      submitLabel: 'Get My Estimate →',
      emptyHint: 'Enter your Calgary address above to get started.',
      noResults: "We couldn't find that address. Check the spelling or try a nearby address.",
      outOfCoverageHeading: 'We only support Calgary right now.',
      outOfCoverageBody:
        "Feasly's cost data covers Calgary addresses only. Try a Calgary address to continue.",
      error: 'Address search is temporarily unavailable. Please try again in a moment.',
      retryLabel: 'Retry',
      searchingLabel: 'Searching addresses…',
    },
    embed: {
      widgetLabel: 'Home building cost estimator',
      loadingLabel: 'Loading estimator…',
      unavailableHeading: 'Estimator unavailable',
      unavailableBody:
        'This estimator is temporarily unavailable — please contact the builder directly.',
      ctaLabel: 'Get my estimate →',
      contactPrefix: 'Questions?',
      poweredBy: 'Powered by Feasly',
    },
    wizard: {
      stepAddress: 'Address',
      stepScope: 'Scope',
      stepDetails: 'Details',
      scopeHeading: 'Configure your build scope',
      scopeSqftLabel: 'Living area',
      scopeSqftHint:
        'Approximate above-grade living area. Most Calgary infills land between 1,800 and 3,500 sq ft — a rough number is fine.',
      scopeSqftUnit: 'sq ft',
      scopeTierLabel: 'Finish tier',
      scopeTierHint:
        'The level of finishes throughout the home. It shapes the estimate range — there are no prices on this page.',
      scopeTiers: [
        {
          id: 'standard',
          name: 'Standard',
          blurb:
            'Durable, builder-grade finishes: quartz-look counters, LVP or carpet flooring, and standard lighting and plumbing packages.',
        },
        {
          id: 'premium',
          name: 'Premium',
          blurb:
            'A clear step up in every room: hardwood and tile, stone counters, upgraded cabinetry, and designer lighting and plumbing fixtures.',
        },
        {
          id: 'luxury',
          name: 'Luxury',
          blurb:
            'Top shelf throughout: custom millwork, natural stone, premium appliances, spa-style bathrooms, and smart-home rough-ins.',
        },
      ],
      scopeBackLabel: '← Back to address',
      scopeCta: 'See My Preview →',
      scopeEmpty: 'No address selected yet.',
      scopeEmptyCta: 'Find your address to start →',
      scopeProjectTypeLabel: 'What are you planning?',
      scopeProjectTypes: [
        {
          id: 'new-build',
          name: 'New Build',
          blurb:
            'A brand-new home on your lot, from foundation to finishes.',
        },
        {
          id: 'renovation',
          name: 'Renovation',
          blurb:
            'Remodel, addition, or basement work on your existing home.',
        },
      ],
      renoSelectedNote:
        'You will describe your renovation — type, area, and finishes — on the next step.',
      renoScopePendingTitle: 'Renovation scope',
      renoScopePendingBody:
        'Renovation scope inputs arrive in the next build. Your project type is saved — come back soon.',
      renoScopeBackLabel: '← Back to project type',
      renoScopeHeading: 'Describe your renovation',
      renoTypeLabel: 'What kind of renovation?',
      renoTypes: [
        {
          id: 'extensive',
          name: 'Extensive remodel',
          blurb: 'Gutting and rebuilding interior spaces — kitchen, baths, whole floors.',
        },
        {
          id: 'addition',
          name: 'Addition',
          blurb: 'Adding new living space to your home (up to 400 sq ft).',
        },
        {
          id: 'basement',
          name: 'Basement',
          blurb: 'Finishing or remodeling your basement.',
        },
        {
          id: 'combined',
          name: 'Combined',
          blurb: 'Kitchen + bath + basement together as one project.',
        },
      ],
      renoSqftLabel: 'Affected area',
      renoSqftHint: 'How many square feet are you renovating?',
      renoSqftUnit: 'sq ft',
      renoAdditionCapNote:
        'Additions over 400 sq ft are quoted as custom projects — enter 400 for the closest estimate.',
      renoSqftClampNote: 'Adjusted to the allowed range.',
      renoTierLabel: 'Finish tier',
      renoTierHint: 'The level of finishes for your renovation.',
      renoUnderpinningLabel: 'Include underpinning (lowering the basement floor)',
      renoUnderpinningBlurb: 'Structural work to increase basement ceiling height.',
      renoPermitNote:
        'Most renovations need a City permit and a 10–15% contingency — your report breaks both out.',
      renoScopeCta: 'See My Preview →',
      renoScopeEmpty: 'No address selected yet.',
      renoScopeEmptyCta: 'Find your address to start →',
      detailsLivingArea: 'Living area',
      detailsFinishTier: 'Finish tier',
      detailsGarage: 'Garage',
      detailsBasement: 'Basement',
      detailsPreviewCta: 'See My Preview →',
      detailsEmpty: 'No address selected yet.',
      detailsEmptyCta: 'Find your address to start →',
      detailsBackLabel: '← Back to scope',
    },
    comparison: {
      landingTitle: 'Compare neighbourhoods',
      landingBody: 'Side-by-side build costs for 2–3 Calgary communities.',
      pickerHeading: 'Compare neighbourhoods',
      pickerSubheading: 'Pick 2–3 Calgary communities to compare side-by-side build costs.',
      searchLabel: 'Find a community',
      searchPlaceholder: 'Search Calgary communities…',
      searchNoResults: 'No communities match your search.',
      selectedLabel: 'Selected communities',
      clearAllLabel: 'Clear all',
      sqftLabel: 'Living area',
      sqftHint: 'Approximate finished square footage for the comparison.',
      sqftUnit: 'sq ft',
      tierLabel: 'Finish tier',
      tierHint: 'Pick the finish level for the comparison.',
      maxCommunitiesNote: 'You can compare up to 3 communities.',
      cta: 'Compare →',
      ctaHint: 'Select at least 2 communities to compare.',
      interimTitle: 'Your comparison is on its way',
      interimBody:
        'We are building the side-by-side comparison for your communities. Check back soon — your picks are saved.',
      interimBackLabel: '← Adjust my picks',
      resultsHeading: 'Side-by-side comparison',
      resultsSubheading: '{count} Calgary communities · {sqft} · {tier}',
      assessedLabel: 'Average City-assessed value (not market value)',
      landLabel: 'Land range',
      buildLabel: 'Build cost',
      totalLabel: 'Total',
      lowestLandBadge: 'Lowest land cost',
      lockedNote: 'Available after email verification',
      unlockCta: 'Unlock Full Numbers →',
      editLabel: '← Edit communities',
      chartTitle: 'Total cost comparison',
      chartAxisNote: 'Bars show the likely total range per community.',
      analyzingValidate: 'Checking your communities…',
      analyzingFetch: 'Fetching City assessed values…',
      analyzingCalculate: 'Calculating side-by-side costs…',
      whatIfLabel: 'What if you change the finish?',
      whatIfHint: 'Re-runs every community at the new finish tier.',
    },
    preview: {
      heading: 'Your estimate preview',
      readyNote: 'Your numbers are ready.',
      backLabel: '← Back to details',
      renoBackLabel: '← Back to scope',
      // RENO-04: reno-specific visible fact labels
      renoTypeLabel: 'Renovation type',
      renoSqftLabel: 'Affected area',
    },
    propertyCard: {
      freshnessMock: 'Sample data for illustration — live City records coming soon',
    },
    report: {
      heading: 'Your build estimate',
      subPreGate: 'Your preview is ready — unlock it to see the full numbers.',
      subPostGate: 'Your personalized build estimate for this Calgary property.',
      totalLabel: 'Total investment',
      planningRangeLabel: 'Likely planning range',
      buildLabel: 'Build cost',
      buildCostNote: 'Construction only — excludes land.',
      landLabel: 'Land (assessed value)',
      landFixedNote: 'City of Calgary assessment · not a cost range',
      lowLabel: 'Low',
      baseLabel: 'Base',
      highLabel: 'High',
      uncalibratedNote:
        'Uncalibrated planning figures — our cost model is not yet calibrated to real builder quotes.',
      lockedNote: 'Locked — unlock to reveal the figures.',
      unlockCta: 'Unlock my full report →',
      pendingSub: 'Your magic link is on its way.',
      pendingNote:
        'We emailed your magic link — click the link in the email to unlock your full numbers.',
      breakdownTitle: 'Where the build budget goes',
      breakdownLocked: 'The breakdown unlocks with your full report.',
      finishLevelLabel: 'Selected finish level',
      tierTitle: 'What if you change the finish tier?',
      tierLockedNote: 'Unlock your report to explore finish tiers.',
      adjustTitle: 'Adjust the size',
      decreaseLabel: 'Decrease square footage',
      increaseLabel: 'Increase square footage',
      adjustHint: 'Tap to change the living area — every figure on this page updates automatically.',
      adjustUnit: 'sq ft',
      adjustCta: 'Re-run estimate',
      adjustLockedNote: 'Unlock your report to adjust the size.',
      updatingLabel: 'Updating your estimate…',
      updatedLabel: 'Updated {date}',
      perSqftUnit: 'per sq ft',
      narrativeTitle: 'AI summary',
      narrativeComingSoon:
        'An AI-written summary of your estimate, the key risks, and what to watch for is coming soon.',
      aiSummaryLocked: 'Unlock your report to read the AI summary of your estimate.',
      stepsTitle: 'Your next 3 steps',
      steps: [
        {
          title: 'Confirm site feasibility',
          body: 'Walk the lot with a builder or designer and confirm setbacks, servicing, and access before you spend on drawings. Surprises live in the site, not the spreadsheet.',
        },
        {
          title: 'Refine your project brief',
          body: 'Lock in your must-haves — size, layout, and finish level. A clear brief is what turns this estimate into quotes you can actually compare.',
        },
        {
          title: 'Meet the right builder',
          body: 'When you are ready, we will introduce you to Calgary infill builders matched to your project. No cold calls, no pressure — an intro only when it helps.',
        },
      ],
      shareTitle: 'Share your estimate',
      shareHint: 'Open an email draft with the current size and exact numbers — your mail app sends it.',
      shareEmailLabel: 'Recipient email',
      shareCta: 'Open email draft',
      shareInvalid: 'Enter a valid email address.',
      shareSubject: 'My Feasly build estimate',
      shareBodyTemplate:
        'Feasly build estimate for {address}:\n\n' +
        'Living area: {sqft} sq ft ({tierLabel} finishes)\n' +
        'Total investment: {total}\n' +
        '{planningRangeLabel}: {rangeLow}–{rangeHigh}\n' +
        '{buildLabel}: {build}\n' +
        '{landLabel}: {land} ({landFixedNote})\n\n' +
        '{bodyClose}',
      shareBodyClose: 'Planning figures only — not a quote.',
      callbackTitle: 'Prefer to talk it through?',
      callbackHint: 'Request a callback and we will walk through the numbers with you.',
      callbackNameLabel: 'Your name',
      callbackPhoneLabel: 'Phone number',
      callbackWindowLabel: 'Preferred time',
      callbackWindows: [
        { id: 'morning', label: 'Morning' },
        { id: 'afternoon', label: 'Afternoon' },
        { id: 'evening', label: 'Evening' },
      ],
      callbackCta: 'Request callback',
      callbackSuccess: 'Callback requested — we will call at your preferred time.',
      callbackError: 'We could not request the callback. Please try again in a moment.',
      callbackInvalid: 'Enter your name and a phone number.',
      pdfCta: 'Download PDF',
      loadingLabel: 'Loading your report…',
      loadError: 'We could not load your report. Please try again in a moment.',
      retryLabel: 'Try again',
      versionLabel: 'Report version',
      // RENO-04: reno-specific report copy (exact copy required by acceptance criteria)
      renoPermitNote: 'Permit and contingency allowances are estimates — confirm with the City of Calgary and your builder.',
      renoDeterministicNote: 'Dollar figures are calculated deterministically from our cost model — not generated by AI.',
      estimateAnotherLabel: 'Estimate another address',
    },
    gate: {
      heading: 'Where should we send your estimate?',
      sub: 'One quick step and your personalized cost report is on its way. We only email what you ask for — no spam, no sales calls.',
      nameLabel: 'Full name',
      namePlaceholder: 'Jane Doe',
      nameRequired: 'Please enter your name.',
      emailLabel: 'Email address',
      emailPlaceholder: 'jane@example.com',
      emailRequired: 'Please enter your email address.',
      emailInvalid: 'That email doesn’t look right — please check it and try again.',
      phoneLabel: 'Phone',
      phonePlaceholder: '(403) 555-0123',
      optionalMarker: '(optional)',
      phoneInvalid: 'That phone number doesn’t look right — digits and basic punctuation only.',
      phonePattern: '^[+()\\-.\\s\\d]{7,20}$',
      timelineLabel: 'When are you hoping to build?',
      timelineLabelReno: 'When are you hoping to renovate?',
      timelinePlaceholder: 'Choose one…',
      timelineOptions: [
        { id: '0-3mo', label: 'Within 3 months' },
        { id: '3-6mo', label: '3–6 months' },
        { id: '6-12mo', label: '6–12 months' },
        { id: '12+mo', label: '12+ months' },
        { id: 'exploring', label: 'Just exploring' },
      ],
      caslLabel:
        'It’s okay to email me occasional updates about Feasly and Calgary infill costs. I can unsubscribe anytime.',
      privacyNote: 'We only use your details to deliver your estimate — never sold, never shared. See our',
      privacyLinkLabel: 'Privacy Policy',
      submitLabel: 'Unlock My Preview →',
      submittingLabel: 'Sending…',
      submitError: 'We couldn’t save your details. Please check your connection and try again.',
      retryLabel: 'Try again',
      backLabel: '← Back to scope',
    },
    analyzing: {
      heading: 'Building your estimate…',
      sub: 'Give us a moment — we’re pulling your property details and running the numbers for real. Nothing here is made up.',
      stageValidate: 'Checking your inputs',
      stageFetch: 'Fetching your City property record',
      stageEstimate: 'Running your cost estimate',
      // RENO-04: reno-specific analyzing step labels (each maps 1:1 to a real awaited call)
      // Order: fetch (property lookup) → scope (reno validation) → estimate (cost calc) → preview (dispatch)
      stageFetchReno: 'Looking up property record…',
      stageScopeReno: 'Measuring the project scope…',
      stageEstimateReno: 'Calculating renovation cost…',
      stagePreviewReno: 'Generating your preview…',
      statusPending: 'Waiting',
      statusActive: 'In progress',
      statusDone: 'Done',
      statusError: 'Failed',
      errorHeading: 'We couldn’t build your estimate',
      errorBody: 'Something went wrong on our end. Nothing was lost — please try again.',
      retryLabel: 'Try again',
    },
    seo: {
      landingTitle: 'Feasly — What will it really cost to build your home in Calgary?',
      landing:
        'A free range-based estimate for your Calgary infill project — land, build, and total investment — in under 2 minutes.',
      scopeTitle: 'Feasly — Configure your build scope',
      scope: 'Set your build size and finish tier for a Calgary infill estimate — step 2 of 3.',
      renoScopeTitle: 'Feasly — Describe your renovation',
      renoScope: 'Describe your Calgary renovation — type, area, and finishes — step 2 of 3.',
      detailsTitle: 'Feasly — Configure your build details',
      details:
        'Configure square footage, finish tier, garage, and basement for your Calgary build estimate — step 3 of 3.',
      previewTitle: 'Feasly — Your estimate preview',
      preview:
        'Your blurred build-cost and total preview for your Calgary infill estimate — unlock the full report.',
      reportTitle: 'Feasly — Your build estimate report',
      report: 'Your range-based Calgary infill build estimate: cost breakdown, tier scenarios, and next steps.',
      sampleReportTitle: 'Feasly — Sample build estimate report (SAMPLE)',
      sampleReport:
        'SAMPLE — a fictional, watermarked example of a Feasly build estimate report. Illustrative figures only, not a real estimate.',
      gateTitle: 'Feasly — Get your estimate',
      gate: 'Enter your details to unlock your personalized Calgary infill cost estimate.',
      analyzingTitle: 'Feasly — Building your estimate',
      analyzing: 'We’re preparing your personalized Calgary infill cost estimate right now.',
      compareTitle: 'Compare neighbourhoods | Feasly',
      compare: 'Compare side-by-side build costs for 2–3 Calgary communities.',
      privacyTitle: 'Feasly — Privacy Policy',
      privacy:
        'How Feasly collects, uses, and protects your information when you generate a build estimate.',
      termsTitle: 'Feasly — Terms of Use',
      terms: 'The terms that apply when you use Feasly to generate a build estimate.',
      howItWorksTitle: 'Feasly — How it works',
      howItWorks:
        'How Feasly builds your Calgary infill estimate in 4 steps: address, scope, preview, unlock. Deterministic math, real City data.',
      faqTitle: 'Feasly — Frequently asked questions',
      faq: 'Is Feasly free? What data do you use? How accurate are estimates? Answers about Calgary infill estimates, privacy, and magic links.',
      developersTitle: 'Feasly — API docs for developers',
      developers:
        'Build on the Feasly API: address-aware property data, deterministic build estimates, and lead capture. Quickstart, auth, scopes, rate limits, errors, sandbox, and the live OpenAPI spec.',
      notFoundTitle: 'Feasly — Page not found',
      notFound: "The page you're looking for moved or never existed.",
      errorTitle: 'Feasly — Something went wrong',
      error: 'Your estimate is safe — try again in a moment.',
    },
    marketing: {
      howItWorks: {
        eyebrow: 'How it works',
        title: 'From address to estimate in about 2 minutes',
        sub: 'No account, no phone calls, no salesperson. Just your address and a few project details.',
        steps: [
          {
            n: '01',
            title: 'Enter your Calgary address',
            body: 'We pull your City of Calgary property record — lot size, zoning, and assessed land value. Only Calgary addresses are supported right now.',
          },
          {
            n: '02',
            title: 'Configure your scope',
            body: 'Tell us about the project: new build or renovation, living area, finish tier, garage, and basement. Rough figures are fine — you can adjust them later.',
          },
          {
            n: '03',
            title: 'Preview your estimate',
            body: 'See a blurred preview of your build-cost range before you share anything. No email required to look.',
          },
          {
            n: '04',
            title: 'Unlock your full report',
            body: 'Enter your email and we send a magic link that unlocks the complete report: total investment, cost breakdown, and next steps. The link is valid for 7 days.',
          },
        ],
        mathNoteTitle: 'Real math, not guesses',
        mathNoteBody:
          'Every dollar figure in your estimate is produced by deterministic math from current cost data and your City property record. Our AI writes the narrative summary only — it never invents prices. Figures are planning ranges, not quotes or appraisals: your final cost depends on your builder, finishes, and market conditions.',
        ctaNewBuild: 'Start a new-build estimate →',
        ctaReno: 'Start a renovation estimate →',
      },
      faq: {
        eyebrow: 'FAQ',
        title: 'Frequently asked questions',
        sub: 'The short answers about Feasly, your data, and your estimate.',
        items: [
          {
            q: 'Is Feasly free?',
            a: 'There is no charge to generate an estimate or unlock your full report.',
          },
          {
            q: 'What data do you use for my estimate?',
            a: 'Your City of Calgary property assessment record (lot size, zoning, assessed land value) plus the project details you enter. Cost figures come from current construction cost data applied with deterministic math — no AI-generated prices.',
          },
          {
            q: 'How accurate are the estimates?',
            a: 'Estimates are planning ranges, not quotes or appraisals. They give you a realistic budget window before you talk to builders. Your final cost depends on your builder, finish choices, and market conditions at build time.',
          },
          {
            q: 'Who sees my information?',
            a: 'Only you, until you ask us to share it. Your email unlocks your report via a magic link; we never sell your information. See our Privacy Policy for the full details.',
          },
          {
            q: 'Do you support addresses outside Calgary?',
            a: 'Not yet — Feasly only supports Calgary addresses right now, because our cost data and property records are Calgary-specific. Enter a non-Calgary address and we’ll tell you plainly instead of guessing.',
          },
          {
            q: 'How does the magic link work?',
            a: 'After you enter your email at the gate, we send a link that unlocks your full report — no password to remember. The link expires after 7 days; if it lapses, just run the estimate again and we’ll send a fresh one.',
          },
        ],
      },
    },
    consent: {
      title: 'A quick word on analytics.',
      body: 'We measure which pages people visit so we can improve Feasly. First-party only — no cookies, no trackers, no selling data. Accept or decline; the site works the same either way.',
      accept: 'Accept analytics',
      decline: 'Decline',
    },
    communities: {
      illustrativeBanner:
        'Illustrative ranges — our cost data is being calibrated. Final figures coming soon.',
      titleTemplate: 'Cost to Build a Home in {name}, Calgary | Feasly',
      descriptionTemplate:
        'Planning cost ranges for building a home in {name}, Calgary — average City-assessed value, Standard/Premium/Luxury build ranges, and FAQs.',
      statLabel: 'Average City-assessed value (not market value)',
      statNote:
        'The average of all City of Calgary property assessment records in this community. Assessments are for tax purposes and can differ from actual sale prices.',
      basisNote:
        'City-assessed basis: land is the community average City-assessed value (a fixed fact, not a range). Build ranges assume 2,400 sqft of above-grade living area.',
      tierSectionTitle: 'What it costs to build in {name}',
      tierSectionSub: 'Planning ranges for a typical new build, by finish tier.',
      faqTitle: 'Common questions',
      faqItems: [
        {
          q: 'What does the cost range cover?',
          a: 'The range covers construction of a typical new home (2,400 sqft above grade) plus the community average City-assessed land value. It is a planning budget, not a builder quote — get your address-specific estimate for figures tuned to your lot.',
        },
        {
          q: 'What is the difference between assessed value and sale price?',
          a: 'The City-assessed value is set by the City of Calgary for property tax purposes. Sale price is what a buyer actually pays. The two often differ — assessments can lag behind real sales. We use assessed values because they are public, consistent, and available for every property.',
        },
        {
          q: 'Why do you show ranges instead of a fixed price?',
          a: 'Build costs depend on choices you have not made yet: your builder, finish tier, and market conditions at build time. A range is the honest answer at this stage. Your address-specific estimate narrows it using your actual lot and project details.',
        },
        {
          q: 'What is not included in these figures?',
          a: 'The ranges exclude demolition of an existing structure, unusual soil or servicing work, permit and development fees beyond typical allowances, financing costs, and GST. Your full report itemizes what is and is not covered.',
        },
        {
          q: 'What is the next step?',
          a: 'Run your address-specific estimate — it takes about 2 minutes and uses your actual City property record. You will get a full report with a three-bucket cost breakdown and your next three steps.',
        },
      ],
      ctaTitle: 'Building in {name}?',
      ctaBody:
        'Get figures for your actual lot — assessed land value, lot size, and zoning pulled from your City property record.',
      ctaLabel: 'Get your address-specific estimate →',
    },
  },
};
