import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { DEFAULT_APP_CONFIG } from './app-config.defaults';
import { CONFIG_URL } from './config-url.token';
import { ConfigService } from './config.service';
describe('ConfigService', () => {
    let service;
    let httpMock;
    let configUrl;
    beforeEach(() => {
        TestBed.configureTestingModule({
            providers: [provideHttpClient(), provideHttpClientTesting()],
        });
        service = TestBed.inject(ConfigService);
        httpMock = TestBed.inject(HttpTestingController);
        configUrl = TestBed.inject(CONFIG_URL);
    });
    it('points at the injected CONFIG_URL token default', () => {
        expect(configUrl).toBe('/assets/config/app-config.json');
    });
    it('honors a CONFIG_URL override without code changes', async () => {
        TestBed.resetTestingModule();
        TestBed.configureTestingModule({
            providers: [
                provideHttpClient(),
                provideHttpClientTesting(),
                { provide: CONFIG_URL, useValue: '/tenant-b/config.json' },
            ],
        });
        const tenantService = TestBed.inject(ConfigService);
        const tenantHttp = TestBed.inject(HttpTestingController);
        const pending = tenantService.load();
        tenantHttp.expectOne('/tenant-b/config.json').flush({ site: { name: 'Tenant B' } });
        await pending;
        expect(tenantService.get('site').name).toBe('Tenant B');
    });
    it('starts with the compiled defaults before load()', () => {
        expect(service.get('wizard').sqftDefault).toBe(DEFAULT_APP_CONFIG.wizard.sqftDefault);
    });
    it('exposes the narrative disclaimer copy verbatim (FE0-001 handoff)', () => {
        expect(service.get('copy').narrativeDisclaimer).toBe('Dollar figures are calculated deterministically from our cost model — not generated by AI.');
    });
    it('loads the JSON and merges it over the defaults', async () => {
        const pending = service.load();
        httpMock.expectOne(configUrl).flush({
            wizard: { sqftDefault: 2500 },
            features: { sampleReport: false },
        });
        await pending;
        expect(service.get('wizard').sqftDefault).toBe(2500);
        // Untouched keys keep their defaults.
        expect(service.get('wizard').sqftMin).toBe(DEFAULT_APP_CONFIG.wizard.sqftMin);
        expect(service.get('features').sampleReport).toBe(false);
        expect(service.get('features').renovationWaitlist).toBe(DEFAULT_APP_CONFIG.features.renovationWaitlist);
    });
    it('ignores unknown keys in the JSON', async () => {
        const pending = service.load();
        httpMock.expectOne(configUrl).flush({ nope: { notReal: 1 } });
        await pending;
        expect('nope' in service.config()).toBe(false);
    });
    it('falls back to compiled defaults when the request fails', async () => {
        const warn = vi.spyOn(console, 'warn').mockImplementation(() => undefined);
        const pending = service.load();
        httpMock.expectOne(configUrl).error(new ProgressEvent('error'));
        await pending;
        expect(service.get('timings').resendCooldownSec).toBe(DEFAULT_APP_CONFIG.timings.resendCooldownSec);
        expect(warn).toHaveBeenCalledOnce();
        warn.mockRestore();
    });
    it('falls back to compiled defaults on malformed JSON', async () => {
        const warn = vi.spyOn(console, 'warn').mockImplementation(() => undefined);
        const pending = service.load();
        // A JSON body that is not an object: merge treats it as "no overrides".
        httpMock.expectOne(configUrl).flush('not json at all', { status: 200, statusText: 'OK' });
        await pending;
        // load() must never reject, and defaults survive.
        expect(service.get('site').name).toBe(DEFAULT_APP_CONFIG.site.name);
        warn.mockRestore();
    });
    it('falls back to compiled defaults when the JSON body is a valid primitive, not an object', async () => {
        const warn = vi.spyOn(console, 'warn').mockImplementation(() => undefined);
        const pending = service.load();
        // Valid JSON, wrong shape: a primitive must never become the AppConfig.
        // (Regression: deepMerge used to return the primitive as the config.)
        httpMock.expectOne(configUrl).flush(5);
        await pending;
        // load() must never reject, and defaults survive.
        expect(service.get('wizard').sqftDefault).toBe(DEFAULT_APP_CONFIG.wizard.sqftDefault);
        expect(service.get('site').name).toBe(DEFAULT_APP_CONFIG.site.name);
        expect(typeof service.config()).toBe('object');
        expect(warn).toHaveBeenCalled();
        warn.mockRestore();
    });
    it('exposes the whole config reactively via the signal', async () => {
        const pending = service.load();
        httpMock.expectOne(configUrl).flush({ site: { name: 'Feasly Test' } });
        await pending;
        expect(service.config().site.name).toBe('Feasly Test');
    });
});
