import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, expect, it } from 'vitest';

/**
 * Regression guard for the missing-SPA-fallback bug found by browser QA
 * (2026-09-24): without `navigationFallback` in staticwebapp.config.json,
 * deep links and refreshes on /estimate/*, /privacy, and /terms served the
 * raw Azure Static Web Apps 404 page instead of the app.
 *
 * SEO-01: platform 404s are overridden to `/index.html` so the branded
 * `/404` SPA route renders; `trailingSlash` is deliberately NOT set —
 * it is global (it would 301 assets, /robots.txt, /sitemap.xml, and
 * /api/* POSTs) and SWA redirect targets are static strings, so the
 * trailing-slash 301s are per-slug exact rules for every prerendered
 * community page (see SEO.md "Trailing-slash policy").
 */
describe('staticwebapp.config.json SPA fallback', () => {
  const configPath = join(
    dirname(fileURLToPath(import.meta.url)),
    '..',
    '..',
    '..',
    '..',
    'public',
    'staticwebapp.config.json',
  );
  const publicDir = dirname(configPath);

  it('exists and is valid JSON', () => {
    expect(existsSync(configPath)).toBe(true);
    expect(() => JSON.parse(readFileSync(configPath, 'utf8'))).not.toThrow();
  });

  it('rewrites all non-file routes to /index.html', () => {
    const config = JSON.parse(readFileSync(configPath, 'utf8')) as {
      navigationFallback?: { rewrite?: string; exclude?: string[] };
    };
    expect(config.navigationFallback?.rewrite).toBe('/index.html');
  });

  it('never rewrites the SEO files or static assets', () => {
    const config = JSON.parse(readFileSync(configPath, 'utf8')) as {
      navigationFallback?: { rewrite?: string; exclude?: string[] };
    };
    const exclude = config.navigationFallback?.exclude ?? [];
    expect(exclude).toContain('/robots.txt');
    expect(exclude).toContain('/sitemap.xml');
    expect(exclude.some((pattern) => pattern.startsWith('/assets'))).toBe(true);
  });

  it('never swallows /api/* into the SPA fallback (P0 2026-09-26)', () => {
    const config = JSON.parse(readFileSync(configPath, 'utf8')) as {
      navigationFallback?: { rewrite?: string; exclude?: string[] };
    };
    const exclude = config.navigationFallback?.exclude ?? [];
    // The SWA has a linked Function App backend: /api/* must reach it.
    // Without this exclusion a missing/stale linked backend silently serves
    // index.html (GET) / 405 (POST) instead of the API.
    expect(exclude).toContain('/api/*');
  });

  it('overrides platform 404s to the SPA shell (branded /404 route)', () => {
    const config = JSON.parse(readFileSync(configPath, 'utf8')) as {
      responseOverrides?: { '404'?: { rewrite?: string } };
    };
    expect(config.responseOverrides?.['404']?.rewrite).toBe('/index.html');
  });

  it('does not set the global trailingSlash flag', () => {
    const config = JSON.parse(readFileSync(configPath, 'utf8')) as {
      trailingSlash?: string;
    };
    // Deliberate: trailing-slash 301s are per-slug exact rules (community
    // pages) in `routes`, not the global flag. A global flag would 301
    // assets, /robots.txt, /sitemap.xml, and /api/* POSTs (see SEO.md).
    expect(config.trailingSlash).toBeUndefined();
  });

  it('301-redirects every prerendered community slug to its trailing-slash form (SEO-01 AC6)', () => {
    const config = JSON.parse(readFileSync(configPath, 'utf8')) as {
      routes?: Array<{ route?: string; redirect?: string; statusCode?: number }>;
    };
    const routes = config.routes ?? [];
    // Every /communities/{slug}/ in prerender-routes.txt must have an exact
    // 301 from the non-trailing-slash form (SWA wildcards would loop, so the
    // rules are per-slug — see SEO.md).
    const prerenderPath = join(publicDir, '..', 'prerender-routes.txt');
    const slugs = readFileSync(prerenderPath, 'utf8')
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line.startsWith('/communities/') && line !== '/communities/')
      .map((line) => line.replace(/\/+$/, ''));
    expect(slugs.length).toBeGreaterThan(0);
    for (const slug of slugs) {
      const rule = routes.find((r) => r.route === slug);
      expect(rule, `missing 301 for ${slug}`).toBeDefined();
      expect(rule?.redirect).toBe(`${slug}/`);
      expect(rule?.statusCode).toBe(301);
    }
  });

  it('every literal excluded path exists in public/ or is build-generated', () => {
    const config = JSON.parse(readFileSync(configPath, 'utf8')) as {
      navigationFallback?: { rewrite?: string; exclude?: string[] };
    };
    // llms.txt / llms-full.txt are generated by the postbuild SEO step
    // (scripts/build-llms-txt.ts), not checked into public/.
    const buildGenerated = new Set(['/llms.txt', '/llms-full.txt']);
    const literal = (config.navigationFallback?.exclude ?? []).filter(
      (pattern) => !pattern.includes('*'),
    );
    for (const path of literal) {
      if (buildGenerated.has(path)) continue;
      expect(existsSync(join(publicDir, path))).toBe(true);
    }
  });
});
