/**
 * Report contracts. Snapshots are immutable — every re-run appends a new one.
 * The narrative disclaimer is a shared constant so UI and API can never drift.
 */
import type { CostRange } from './common';
import type { CostRow, EstimateInputs, FinishTier } from './estimate';

/** Verbatim footer on every AI narrative. Copy-lint enforced. */
export const NARRATIVE_DISCLAIMER =
  'Dollar figures are calculated deterministically from our cost model — not generated by AI.';

export interface ReportSnapshot {
  readonly snapshotId: string;
  readonly estimateId: string;
  readonly leadId: string;
  readonly inputs: EstimateInputs;
  /** Always real ranges here — snapshots exist only post-gate. */
  readonly buildRange: CostRange;
  readonly totalRange: CostRange;
  readonly landRange: CostRange;
  readonly rows: readonly CostRow[];
  readonly narrative: string;
  readonly preparedAt: string;
  /** Monotonic per estimateId. */
  readonly version: number;
}

export interface TierRevisionRequest {
  readonly tier?: FinishTier;
  readonly sqft?: number;
}

export type TierRevisionResponse = ReportSnapshot;
