import { TestBed } from '@angular/core/testing';
import { describe, expect, it } from 'vitest';
import type { CostRow } from '@feasly/contracts';
import { mockReport } from '../../core/api/mock-data';
import { ReportPdfService, sanitizePdfText, type ReportPdfInput } from './report-pdf.service';

/**
 * ReportPdfService renders the verified snapshot to a real PDF via jsPDF
 * (lazy-loaded). The service owns layout; the component owns the download
 * plumbing and UI states.
 */
describe('ReportPdfService', () => {
  function input(overrides: Partial<ReportPdfInput> = {}): ReportPdfInput {
    const snapshot = mockReport(
      'estimate-1',
      'lead-1',
      { sqft: 2200, tier: 'premium', garage: 'double', basement: 'unfinished' },
      'Dollar figures are calculated deterministically from our cost model — not generated by AI.',
    );
    return {
      snapshot,
      address: '2631 63 Ave SW, Calgary, AB',
      title: 'New-build cost report',
      preparedLine: 'Prepared September 27, 2026',
      versionLine: 'Report version 3',
      steps: [
        { title: 'Meet your matched builder', body: 'We can connect you.' },
        { title: 'Refine your project brief', body: 'Lock in must-haves.' },
      ],
      disclaimer: 'Dollar figures are calculated deterministically from our cost model — not generated by AI.',
      uncalibratedNote: 'Uncalibrated planning figures.',
      ...overrides,
    };
  }

  it('generates a non-empty PDF blob with the PDF magic bytes', async () => {
    const service = TestBed.inject(ReportPdfService);
    const blob = await service.generate(input());
    expect(blob).toBeInstanceOf(Blob);
    expect(blob.type).toBe('application/pdf');
    expect(blob.size).toBeGreaterThan(1000);
    expect(await blob.slice(0, 5).text()).toBe('%PDF-');
  });

  it('embeds the address, version, and formatted figures in the PDF content', async () => {
    const service = TestBed.inject(ReportPdfService);
    const blob = await service.generate(input());
    // jsPDF encodes body text as literal WinAnsi strings, so distinctive
    // content is searchable in the raw output.
    const raw = await blob.text();
    expect(raw).toContain('2631 63 Ave SW, Calgary, AB');
    expect(raw).toContain('Report version 3');
    expect(raw).toContain('Feasly');
  });

  it('renders the honest empty-narrative fallback instead of inventing text', async () => {
    const service = TestBed.inject(ReportPdfService);
    const empty = input();
    const blob = await service.generate({
      ...empty,
      snapshot: { ...empty.snapshot, narrative: '   ' },
    });
    const raw = await blob.text();
    expect(raw).toContain('the figures above are the complete estimate');
  });

  it('includes the coverage framing and the landscaping-only exclusion', async () => {
    const service = TestBed.inject(ReportPdfService);
    const blob = await service.generate(input());
    const raw = await blob.text();
    // jsPDF WinAnsi-encodes body text; assert on ASCII-safe substrings.
    expect(raw).toContain('60+ line items');
    expect(raw).toContain('not in this estimate');
    // Landscaping is the only exclusion (Karan 2026-09-28).
    expect(raw).toContain('Landscaping');
    expect(raw).not.toContain('Demolition of any existing home');
    expect(raw).not.toContain('Financing costs');
  });

  it('omits the new-build exclusions on a renovation snapshot', async () => {
    const service = TestBed.inject(ReportPdfService);
    const renoInput = input();
    const blob = await service.generate({
      ...renoInput,
      title: 'Renovation estimate',
      snapshot: { ...renoInput.snapshot, projectType: 'renovation' as const },
    });
    const raw = await blob.text();
    // New-build coverage framing must not leak onto reno PDFs.
    expect(raw).not.toContain('60+ line items');
    expect(raw).not.toContain('not in this estimate');
    expect(raw).not.toContain('Demolition of any existing home');
  });

  it('strips control characters so jsPDF stays in WinAnsi (QA bug: feasly-estimate-1.pdf narrative clipped)', async () => {
    const service = TestBed.inject(ReportPdfService);
    const dirty = input();
    const blob = await service.generate({
      ...dirty,
      snapshot: {
        ...dirty.snapshot,
        // A stray \x11 (DC1) mid-word is what jsPDF 4.x choked on: one
        // non-WinAnsi char flips the whole line to UTF-16BE (NUL-interleaved)
        // and the line renders ~2x too wide, clipped at the page edge.
        narrative:
          'Sunalta is a well\x11e\x00s\x00tablished inner city neighbourhood.\x0BFees are calculated deterministically.',
      },
    });
    const raw = await blob.text();
    // No UTF-16BE (NUL-interleaved) text anywhere in the output.
    expect(raw).not.toContain('\x00');
    // Words intact after the control chars are stripped.
    expect(raw).toContain('Sunalta is a wellestablished inner city neighbourhood.');
    expect(raw).toContain('Fees are calculated deterministically.');
  });

  it('renders the same three cost buckets as the report page, land excluded', async () => {
    const service = TestBed.inject(ReportPdfService);
    // The 10 raw engine rows of a real snapshot, including the land row that
    // the PDF used to dump verbatim (QA bug: breakdown did not match the page).
    const rows: CostRow[] = [
      { key: 'land', label: 'Land (assessed value)', range: { low: 4930000, base: 4930000, high: 4930000 } },
      { key: 'hard.framing', label: 'Framing & structure', range: { low: 80000, base: 90000, high: 100000 } },
      { key: 'hard.foundation', label: 'Foundation', range: { low: 59000, base: 66000, high: 73000 } },
      { key: 'hard.envelope', label: 'Envelope (roof, siding, windows)', range: { low: 65000, base: 72000, high: 79000 } },
      { key: 'hard.sitePrep', label: 'Site preparation & excavation', range: { low: 41000, base: 46000, high: 51000 } },
      { key: 'hard.finishes', label: 'Interior finishes', range: { low: 108000, base: 120000, high: 132000 } },
      { key: 'hard.mep', label: 'Mechanical, electrical & plumbing', range: { low: 61000, base: 68000, high: 75000 } },
      { key: 'soft.design', label: 'Design & engineering', range: { low: 23000, base: 26000, high: 29000 } },
      { key: 'soft.permits', label: 'Permits & fees', range: { low: 5000, base: 7000, high: 9000 } },
      { key: 'contingency', label: 'Contingency', range: { low: 52000, base: 52803, high: 52803 } },
    ];
    const bucketed = input();
    const blob = await service.generate({
      ...bucketed,
      snapshot: { ...bucketed.snapshot, rows },
    });
    // jsPDF escapes parens in literal strings (\( \)); normalize so label
    // assertions read like the on-screen text.
    const raw = (await blob.text()).replace(/\\\(/g, '(').replace(/\\\)/g, ')');
    // Exactly the three bucket labels the report page renders.
    expect(raw).toContain('Structure & exterior');
    expect(raw).toContain('Interior & home systems');
    expect(raw).toContain('Design, permits & contingency');
    // Each bucket's base figure, summed from the raw rows (land excluded).
    expect(raw).toContain('$274,000'); // 90k+66k+72k+46k
    expect(raw).toContain('$188,000'); // 120k+68k
    expect(raw).toContain('$85,803'); // 26k+7k+52,803
    // No per-row dump, and no land breakdown row duplicating the summary's.
    expect(raw).not.toContain('Land (assessed value)');
    expect(raw).not.toContain('Framing & structure');
    expect(raw).not.toContain('Interior finishes');
    // Land still has its own figure in the summary section.
    expect(raw).toContain('Land (City assessed value)');
  });
});

describe('sanitizePdfText', () => {
  it('strips C0 controls, DEL and C1 controls but preserves newlines and tabs', () => {
    expect(sanitizePdfText('a\x11b\x00c\x7Fd\u0085e')).toBe('abcde');
    expect(sanitizePdfText('line1\nline2\tline3')).toBe('line1\nline2\tline3');
    expect(sanitizePdfText('plain text')).toBe('plain text');
  });
});
