import { TestBed } from '@angular/core/testing';
import { describe, expect, it } from 'vitest';
import { mockReport } from '../../core/api/mock-data';
import { ReportPdfService, type ReportPdfInput } from './report-pdf.service';

/**
 * ReportPdfService renders the verified snapshot to a real PDF via jsPDF
 * (lazy-loaded). The service owns layout; the component owns the download
 * plumbing and UI states.
 */
describe('ReportPdfService', () => {
  function input(overrides: Partial<ReportPdfInput> = {}): ReportPdfInput {
    const snapshot = mockReport(
      'estimate-1',
      'lead-1',
      { sqft: 2200, tier: 'premium', garage: 'double', basement: 'unfinished' },
      'Dollar figures are calculated deterministically from our cost model — not generated by AI.',
    );
    return {
      snapshot,
      address: '2631 63 Ave SW, Calgary, AB',
      title: 'New-build cost report',
      preparedLine: 'Prepared September 27, 2026',
      versionLine: 'Report version 3',
      steps: [
        { title: 'Meet your matched builder', body: 'We can connect you.' },
        { title: 'Refine your project brief', body: 'Lock in must-haves.' },
      ],
      disclaimer: 'Dollar figures are calculated deterministically from our cost model — not generated by AI.',
      uncalibratedNote: 'Uncalibrated planning figures.',
      ...overrides,
    };
  }

  it('generates a non-empty PDF blob with the PDF magic bytes', async () => {
    const service = TestBed.inject(ReportPdfService);
    const blob = await service.generate(input());
    expect(blob).toBeInstanceOf(Blob);
    expect(blob.type).toBe('application/pdf');
    expect(blob.size).toBeGreaterThan(1000);
    expect(await blob.slice(0, 5).text()).toBe('%PDF-');
  });

  it('embeds the address, version, and formatted figures in the PDF content', async () => {
    const service = TestBed.inject(ReportPdfService);
    const blob = await service.generate(input());
    // jsPDF encodes body text as literal WinAnsi strings, so distinctive
    // content is searchable in the raw output.
    const raw = await blob.text();
    expect(raw).toContain('2631 63 Ave SW, Calgary, AB');
    expect(raw).toContain('Report version 3');
    expect(raw).toContain('Feasly');
  });

  it('renders the honest empty-narrative fallback instead of inventing text', async () => {
    const service = TestBed.inject(ReportPdfService);
    const empty = input();
    const blob = await service.generate({
      ...empty,
      snapshot: { ...empty.snapshot, narrative: '   ' },
    });
    const raw = await blob.text();
    expect(raw).toContain('the figures above are the complete estimate');
  });

  it('includes the coverage framing and the landscaping-only exclusion', async () => {
    const service = TestBed.inject(ReportPdfService);
    const blob = await service.generate(input());
    const raw = await blob.text();
    // jsPDF WinAnsi-encodes body text; assert on ASCII-safe substrings.
    expect(raw).toContain('60+ line items');
    expect(raw).toContain('not in this estimate');
    // Landscaping is the only exclusion (Karan 2026-09-28).
    expect(raw).toContain('Landscaping');
    expect(raw).not.toContain('Demolition of any existing home');
    expect(raw).not.toContain('Financing costs');
  });

  it('omits the new-build exclusions on a renovation snapshot', async () => {
    const service = TestBed.inject(ReportPdfService);
    const renoInput = input();
    const blob = await service.generate({
      ...renoInput,
      title: 'Renovation estimate',
      snapshot: { ...renoInput.snapshot, projectType: 'renovation' as const },
    });
    const raw = await blob.text();
    // New-build coverage framing must not leak onto reno PDFs.
    expect(raw).not.toContain('60+ line items');
    expect(raw).not.toContain('not in this estimate');
    expect(raw).not.toContain('Demolition of any existing home');
  });
});
