/**
 * Compile-time contract assertions (FE0-001). There is no test runner in this
 * package by design — these assertions run under `tsc --noEmit` (`npm test`).
 * If a contract shape drifts, the build fails here first.
 */
import type {
  AnalyticsEvent,
  AutocompleteSuggestion,
  BlurredFigure,
  CallbackRequest,
  CommunityAggregate,
  CostRange,
  EmbedTenantConfig,
  EstimateRequest,
  EstimateResponse,
  Figure,
  LeadRequest,
  MagicLinkVerifyResponse,
  PartnerShareRequest,
  PropertyRecord,
  ReportSnapshot,
  TierRevisionRequest,
} from '../src';
import {
  CONTRACT_NAMES,
  NARRATIVE_DISCLAIMER,
  isBlurred,
  isCostRange,
} from '../src';

// --- tiny assertion helpers (compile-time only) ---
function assertType<T>(value: T): void {
  void value;
}

// --- Figure narrowing: the blur contract ---
declare const fig: Figure;
if (isBlurred(fig)) {
  assertType<BlurredFigure>(fig);
} else {
  assertType<CostRange>(fig);
}
assertType<boolean>(isCostRange(fig));
// Negative assertions: @ts-expect-error fails the build if these ever BECOME
// assignable, which is exactly the drift we want to catch.
// @ts-expect-error — BlurredFigure must never satisfy CostRange
const notARange: CostRange = { blurred: true } as BlurredFigure;
// @ts-expect-error — CostRange must never satisfy BlurredFigure
const notBlurred: BlurredFigure = { low: 1, high: 2 } as CostRange;
void notARange;
void notBlurred;

// --- every domain shape is constructible and closed ---
declare const property: PropertyRecord;
assertType<string>(property.addressKey);
assertType<number | null>(property.yearBuilt);
assertType<boolean>(property.stale);

declare const suggestion: AutocompleteSuggestion;
assertType<string>(suggestion.addressKey);

declare const estimateReq: EstimateRequest;
assertType<'standard' | 'premium' | 'luxury'>(estimateReq.tier);
assertType<'none' | 'double' | 'triple'>(estimateReq.garage);
assertType<'unfinished' | 'finished'>(estimateReq.basement);

declare const estimateRes: EstimateResponse;
assertType<Figure>(estimateRes.figures.build);
assertType<Figure>(estimateRes.figures.total);
assertType<readonly { readonly key: string }[]>(estimateRes.rows);

declare const leadReq: LeadRequest;
assertType<string | undefined>(leadReq.phone);
assertType<string | undefined>(leadReq.tenantKey);
assertType<boolean>(leadReq.marketingConsent);

declare const verifyRes: MagicLinkVerifyResponse;
if (verifyRes.valid) {
  assertType<string>(verifyRes.reportToken);
} else {
  assertType<'expired' | 'invalid'>(verifyRes.reason);
}

declare const snapshot: ReportSnapshot;
assertType<CostRange>(snapshot.buildRange); // snapshots are always post-gate: real ranges
assertType<number>(snapshot.version);

declare const revision: TierRevisionRequest;
assertType<'standard' | 'premium' | 'luxury' | undefined>(revision.tier);

declare const callback: CallbackRequest;
assertType<'morning' | 'afternoon' | 'evening'>(callback.window);

declare const share: PartnerShareRequest;
assertType<string>(share.partnerEmail);

// Analytics payload is closed: only event/route/ts exist.
declare const event: AnalyticsEvent;
assertType<
  | 'step_view'
  | 'gate_view'
  | 'gate_convert'
  | 'report_open'
  | 'tier_toggle'
  | 'callback_request'
  | 'partner_share'
  | 'pdf_download'
>(event.event);
const eventKeys = ['event', 'route', 'ts'] as const;
assertType<readonly ['event', 'route', 'ts']>(eventKeys);
assertType<3>(eventKeys.length);

declare const tenant: EmbedTenantConfig;
assertType<string>(tenant.allowedOrigin);

declare const community: CommunityAggregate;
assertType<number>(community.avgAssessedValue);

// --- shared constants ---
assertType<'Dollar figures are calculated deterministically from our cost model — not generated by AI.'>(
  NARRATIVE_DISCLAIMER,
);

// --- registry covers every contract module ---
const names = CONTRACT_NAMES;
assertType<12>(names.length);
