import { describe, expect, it } from 'vitest';
import { narrativeDisplayParagraphs } from './narrative-display';

describe('narrativeDisplayParagraphs', () => {
  it('passes new plain-text narratives through as paragraphs', () => {
    const paras = narrativeDisplayParagraphs(
      'Coventry Hills is a family-oriented community in northeast Calgary.\n\n' +
        'Schools in the area rate well with parents.\n\n' +
        'Dollar figures are calculated deterministically from our cost model — not generated by AI.',
    );
    expect(paras).toEqual([
      'Coventry Hills is a family-oriented community in northeast Calgary.',
      'Schools in the area rate well with parents.',
      'Dollar figures are calculated deterministically from our cost model — not generated by AI.',
    ]);
  });

  it('returns [] for empty input', () => {
    expect(narrativeDisplayParagraphs('')).toEqual([]);
    expect(narrativeDisplayParagraphs('   \n  ')).toEqual([]);
  });

  it('keeps the compliance footer as its own paragraph (no fusing)', () => {
    const paras = narrativeDisplayParagraphs(
      'Some neighbourhood prose here.\n\nDollar figures are calculated deterministically from our cost model — not generated by AI.',
    );
    expect(paras).toHaveLength(2);
    expect(paras[1]).toBe(
      'Dollar figures are calculated deterministically from our cost model — not generated by AI.',
    );
  });

  it('cleans legacy markdown: bold markers, inline --- separators, pipe tables', () => {
    const paras = narrativeDisplayParagraphs(
      '**Coventry Hills – What you\'ll love** Coventry Hills is quiet. --- **Cost estimate** | Item | Low | |------|-----| | Land | $652,000 |',
    );
    expect(paras).toEqual([
      "Coventry Hills – What you'll love Coventry Hills is quiet.",
      'Cost estimate · Item · Low',
      'Land · $652,000',
    ]);
  });

  it('collapses an exactly-duplicated narrative to one copy (B2)', () => {
    const guide =
      'Coventry Hills is a family-oriented community.\n\nSchools rate well with parents.';
    const paras = narrativeDisplayParagraphs(`${guide}\n\n${guide}`);
    expect(paras).toEqual([
      'Coventry Hills is a family-oriented community.',
      'Schools rate well with parents.',
    ]);
  });

  it('drops consecutive duplicate paragraphs', () => {
    const paras = narrativeDisplayParagraphs('First para.\n\nFirst para.\n\nSecond para.');
    expect(paras).toEqual(['First para.', 'Second para.']);
  });

  it('does not dedupe a narrative whose halves merely resemble each other', () => {
    const paras = narrativeDisplayParagraphs(
      'Coventry Hills is quiet.\n\nCoventry Hills is quiet and leafy.',
    );
    expect(paras).toHaveLength(2);
  });

  it('renders a truncated-then-footer legacy narrative as separate clean paragraphs (B3)', () => {
    const paras = narrativeDisplayParagraphs(
      'Coventry Hills is a family-oriented community.\n\n- **Transit\n\nDollar figures are calculated deterministically from our cost model — not generated by AI.',
    );
    expect(paras).toEqual([
      'Coventry Hills is a family-oriented community.',
      '- Transit',
      'Dollar figures are calculated deterministically from our cost model — not generated by AI.',
    ]);
  });
});
