/**
 * Common-password blocklist (auth/01).
 *
 * A curated set of the most-abused passwords plus Feasly/brand terms.
 * Checked in so there is no external API dependency at request time.
 * Candidates are lowercased before lookup; extend by appending lines.
 */
export const COMMON_PASSWORDS: ReadonlySet<string> = new Set(
  [
    // Brand / product terms (always blocked, any casing).
    'feasly',
    'feasly2026',
    'feasly123',
    'elitecraft',
    'elite-craft',
    'builder123',
    'calgary123',
    // The usual suspects — top of every breach corpus.
    'password',
    'password1',
    'password12',
    'password123',
    'password1234',
    'password12345',
    'passw0rd',
    'p@ssw0rd',
    'p@ssword123',
    '123456',
    '1234567',
    '12345678',
    '123456789',
    '1234567890',
    '123123',
    '123321',
    '12345',
    '1234',
    '111111',
    '11111111',
    '000000',
    '00000000',
    'qwerty',
    'qwerty123',
    'qwertyuiop',
    'asdfghjkl',
    'zxcvbnm',
    '1q2w3e4r',
    '1qaz2wsx',
    'qazwsx',
    'letmein',
    'letmein123',
    'welcome',
    'welcome1',
    'welcome123',
    'admin',
    'admin123',
    'admin1234',
    'administrator',
    'root',
    'toor',
    'changeme',
    'changeme123',
    'default',
    'login',
    'login123',
    'master',
    'master123',
    'monkey',
    'dragon',
    'football',
    'baseball',
    'basketball',
    'superman',
    'batman',
    'trustno1',
    'iloveyou',
    'iloveyou123',
    'princess',
    'sunshine',
    'shadow',
    'michael',
    'jennifer',
    'jordan',
    'hunter',
    'charlie',
    'andrew',
    'robert',
    'thomas',
    'daniel',
    'pepper',
    'ginger',
    'freedom',
    'whatever',
    'nothing',
    'secret',
    'secret123',
    'mustang',
    'access',
    'access123',
    // Keyboard walks and repeats.
    'aaaaaa',
    'aaaaaaaa',
    'aaaaaaaaaa',
    'abcdefg',
    'abcdefgh',
    'abc123',
    'abc12345',
    '!@#$%^&*',
    '1q2w3e4r5t',
    // Years and seasons people actually use.
    'summer2024',
    'summer2025',
    'summer2026',
    'winter2024',
    'winter2025',
    'winter2026',
    'spring2026',
    'autumn2026',
    'fall2026',
    'january2026',
    '2026password',
    // Company-flavored defaults.
    'company123',
    'test123',
    'test1234',
    'demo123',
    'temp123',
    'user123',
    'guest123',
  ].map((p) => p.toLowerCase()),
);

/** True when the candidate (any casing) is on the blocklist. */
export function isCommonPassword(candidate: string): boolean {
  return COMMON_PASSWORDS.has(candidate.toLowerCase());
}
