import {
  Component,
  inject,
  OnInit,
  viewChild,
  ChangeDetectorRef,
  ViewContainerRef,
} from '@angular/core';
import {
  ActivatedRoute,
  Router,
  RouterLink,
  type ResolveFn,
} from '@angular/router';
import { Meta } from '@angular/platform-browser';
import { ConfigService } from '../../core/config';
import { SeoService } from '../../core/seo';
import { buildFaqPageSchema, buildLocalBusinessSchema } from '../../core/seo/jsonld-schemas';
import { SiteFooterComponent, SiteNavComponent } from '../../shared/components';
import type {
  CommunityProfileCopy,
  CommunityProfileView,
  CommunityType,
} from '@feasly/contracts';
import type { CommunityProfilePageComponent } from './community-profile-page.component';
import { toDisplayName } from './community-names';

interface TierRow {
  key: 'standard' | 'premium' | 'luxury';
  label: string;
  buildLow: number;
  buildHigh: number;
  landValue: number;
  totalLow: number;
  totalHigh: number;
}

interface CommunityView {
  slug: string;
  name: string;
  displayName: string;
  count: number;
  avgAssessedValue: number;
  avgLotSqft: number;
  tiers: TierRow[];
}

/**
 * Per-slug page data (generated by `scripts/build-community-pages.ts`).
 * One small JSON per community — the component dynamically imports only its
 * own slug's file, so the full 40-community aggregates/ranges JSONs never
 * enter the client bundle.
 */
export interface CommunityPageData {
  slug: string;
  type: CommunityType;
  assessmentYear: string;
  aggregate: {
    slug: string;
    name: string;
    count: number;
    avgAssessedValue: number;
    avgLotSqft: number;
  };
  range: {
    slug: string;
    tiers: Record<'standard' | 'premium' | 'luxury', Omit<TierRow, 'key' | 'label'>>;
    costDataVersion: string;
    calibrated: boolean;
    buildSqft: number;
  } | null;
  nearby: Array<{ slug: string; name: string }>;
  mix?: {
    dwellingUnits: number;
    mix: { singleDetached: number; semiDuplex: number; multiFamily: number };
    mostCommonType: string;
  };
}

/**
 * Route resolver: loads the slug's page-data JSON before the component
 * activates. Vite code-splits the dynamic import — each slug gets its own
 * tiny chunk (~0.5KB), fetched on demand. Runs on the server during
 * prerendering too, so SEO HTML is complete.
 *
 * Returns null for unknown slugs (the component redirects to the 404).
 */
export interface CommunityPageResolved {
  readonly pageData: CommunityPageData;
  /** Preloaded profile component class (only for type='profile'). Passed via
   * resolver so ngOnInit can create it synchronously during SSR/prerender —
   * dynamic import in ngOnInit doesn't complete before serialization. */
  readonly profileComponent?: typeof import('./community-profile-page.component').CommunityProfilePageComponent;
  /** Preloaded resolveProfileCopy fn (only for type='profile'). */
  readonly resolveProfileCopy?: typeof import('./community-profile-page.component').resolveProfileCopy;
  /** Preloaded raw profile copy (only for type='profile'). */
  readonly profileCopyRaw?: import('@feasly/contracts').RawCommunityProfileCopy;
}

export const communityPageResolver: ResolveFn<CommunityPageResolved | null> = async (route) => {
  const slug = route.paramMap.get('slug') ?? '';
  // Validate the slug to prevent path traversal — only lowercase alphanumerics and hyphens.
  if (!/^[a-z0-9-]+$/.test(slug)) {
    return null;
  }
  try {
    const mod = await import(`../../../content/data/community-pages/${slug}.json`);
    const pageData = (mod.default ?? mod) as CommunityPageData;
    if (pageData.type === 'profile') {
      const [profileMod, copyMod] = await Promise.all([
        import('./community-profile-page.component'),
        import('./community-profile-copy.defaults'),
      ]);
      return {
        pageData,
        profileComponent: profileMod.CommunityProfilePageComponent,
        resolveProfileCopy: profileMod.resolveProfileCopy,
        profileCopyRaw: copyMod.DEFAULT_COMMUNITY_PROFILE_COPY,
      };
    }
    return { pageData };
  } catch {
    return null;
  }
};

/**
 * Community page (SEO-04): `/communities/:slug/`.
 *
 * Two variants, chosen by the community's type in its per-slug page-data
 * JSON (generated by `scripts/build-community-pages.ts`; the component
 * dynamically imports only its own slug's ~0.5KB file — the full
 * 40-community aggregates/ranges JSONs never enter the client bundle):
 * - `build-guide`: the single-family build-cost guide — real average
 *   City-assessed value, build-cost ranges per finish tier (computed at build
 *   time by the frozen cost engine — this component never sees per-sqft rates
 *   or calibration params), a 5-question FAQ, and a CTA to the address step.
 * - `profile`: condo/apartment-dominated communities where a per-house build
 *   figure would be misleading — a property-values profile instead (average
 *   assessed value, dwelling mix, assessment explainer, assessment FAQs).
 *   Never renders build prices.
 *
 * Data arrives via `communityPageResolver` (see above) before activation —
 * the component reads it synchronously from `ActivatedRoute.data`, so
 * server prerendering and client hydration see identical state.
 *
 * Prerendered for every slug. All figures are planning ranges / assessment
 * records, not quotes. When the cost data is still uncalibrated, an
 * illustrative banner is shown on guide pages.
 */
@Component({
  selector: 'app-community-page',
  standalone: true,
  imports: [RouterLink, SiteFooterComponent, SiteNavComponent],
  templateUrl: './community-page.component.html',
  styleUrl: './community-page.component.scss',
})
export class CommunityPageComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly seo = inject(SeoService);
  private readonly meta = inject(Meta);
  private readonly config = inject(ConfigService);

  /** Static page copy (config-owned). */
  readonly copy = this.config.get('copy').communities;

  /** The community being rendered, or null when the slug is unknown. */
  community: CommunityView | null = null;

  /** Profile variant view + resolved copy (null for build-guide pages). */
  profileView: CommunityProfileView | null = null;
  profileCopy: CommunityProfileCopy | null = null;

  /**
   * Anchor for the lazily-created profile variant. `NgComponentOutlet`
   * cannot be used here: it never instantiates a component whose class
   * arrives asynchronously after first change detection, so the profile
   * component is created imperatively once its chunk loads.
   */
  private readonly profileHost = viewChild('profileHost', { read: ViewContainerRef });
  private readonly cdr = inject(ChangeDetectorRef);

  /** Cost-data version for the meta tag (from the page-data JSON). */
  costDataVersion = '';

  /** Whether the figures are calibrated (hides the illustrative banner). */
  calibrated = false;

  /** Build sqft the ranges assume (from the page-data JSON, not hardcoded). */
  buildSqft = 0;

  /** FAQ items from config (short alias for the template). */
  get faqs(): { q: string; a: string }[] {
    return this.copy.faqItems;
  }

  ngOnInit(): void {
    const resolved = this.route.snapshot.data['pageData'] as CommunityPageResolved | null;
    const pageData = resolved?.pageData ?? null;
    if (!pageData) {
      // Unknown slug — the branded 404 route (path is a route, not a tunable).
      void this.router.navigate([NOT_FOUND_PATH]);
      return;
    }
    const view = this.buildView(pageData);
    if (!view) {
      void this.router.navigate([NOT_FOUND_PATH]);
      return;
    }
    // Cost-data metadata lives in the page-data JSON (per-slug file carries
    // the range row's version/calibration fields).
    this.costDataVersion = pageData.range?.costDataVersion ?? '';
    this.calibrated = pageData.range?.calibrated ?? false;
    this.buildSqft = pageData.range?.buildSqft ?? 0;

    if (pageData.type === 'profile') {
      // resolved is non-null here (pageData came from it).
      this.renderProfileSync(view, pageData, resolved as CommunityPageResolved);
      return;
    }
    this.community = view;
    const title = this.copy.titleTemplate.replace('{name}', view.displayName);
    // The meta description carries the real per-community assessed value so
    // all community pages have unique descriptions in search results
    // (template-only copy would be near-duplicate across pages).
    const description = this.copy.descriptionTemplate
      .replace('{name}', view.displayName)
      .replace('{avgAssessed}', this.formatCad(view.avgAssessedValue));
    this.seo.setPage({
      title,
      description,
      path: `/communities/${view.slug}/`,
    });
    this.meta.updateTag({ name: 'feasly:cost-data-version', content: this.costDataVersion });
    // SEO-06: FAQPage + LocalBusiness JSON-LD for rich results.
    const pagePath = `/communities/${view.slug}/`;
    this.seo.setJsonLdScript('faq', buildFaqPageSchema(this.copy.faqItems));
    this.seo.setJsonLdScript(
      'business',
      buildLocalBusinessSchema(this.seo.getSiteUrl(), `${this.seo.getSiteUrl()}${pagePath}`),
    );
  }

  /** Interpolates the community name into a copy template. */
  fill(template: string): string {
    return template.replace('{name}', this.community?.displayName ?? '');
  }

  /** Formats whole CAD dollars (no cents — money is integer downstream). */
  formatCad(value: number): string {
    return new Intl.NumberFormat('en-CA', {
      style: 'currency',
      currency: 'CAD',
      maximumFractionDigits: 0,
    }).format(value);
  }

  /**
   * Land's share of the tier total as a 0–100 percentage, computed against
   * the build-range midpoint (land is a fixed value, build is a range).
   * Drives the CSS-only land-vs-build split bar.
   */
  landSharePct(tier: TierRow): number {
    const buildMid = (tier.buildLow + tier.buildHigh) / 2;
    const total = tier.landValue + buildMid;
    return total > 0 ? (tier.landValue / total) * 100 : 0;
  }

  /** Build's share of the tier total — the complement of landSharePct. */
  buildSharePct(tier: TierRow): number {
    return 100 - this.landSharePct(tier);
  }

  /**
   * Text equivalent for the split bar (the bar must never be color-only
   * for assistive tech). Interpolates the config-owned label template.
   */
  splitBarLabel(tier: TierRow): string {
    const landPct = Math.round(this.landSharePct(tier));
    return this.copy.splitBarLabelTemplate
      .replace('{land}', this.formatCad(tier.landValue))
      .replace('{landPct}', String(landPct))
      .replace('{build}', `${this.formatCad(tier.buildLow)}–${this.formatCad(tier.buildHigh)}`)
      .replace('{buildPct}', String(100 - landPct));
  }

  /**
   * Renders the property-profile variant synchronously (for SSR/prerender).
   * The profile component class and copy are preloaded by the resolver —
   * no dynamic import here, so the content exists before serialization.
   * Builds the view model from the page-data JSON (mix + nearby are already
   * in the per-slug file), and sets profile SEO with FAQPage JSON-LD.
   */
  private renderProfileSync(
    view: CommunityView,
    pageData: CommunityPageData,
    resolved: CommunityPageResolved,
  ): void {
    const ProfileComponent = resolved.profileComponent;
    const resolveFn = resolved.resolveProfileCopy;
    const profileCopyRaw = resolved.profileCopyRaw;
    if (!ProfileComponent || !resolveFn || !profileCopyRaw) {
      return;
    }
    const mix = pageData.mix;
    const nearby = pageData.nearby.map((n) => ({
      slug: n.slug,
      displayName: toDisplayName(n.name),
    }));
    const profileView: CommunityProfileView = {
      slug: view.slug,
      displayName: view.displayName,
      avgAssessedValue: view.avgAssessedValue,
      assessmentYear: pageData.assessmentYear,
      dwellingUnits: mix?.dwellingUnits ?? 0,
      mix: mix?.mix ?? { singleDetached: 0, semiDuplex: 0, multiFamily: 0 },
      mostCommonType: (mix?.mostCommonType as CommunityProfileView['mostCommonType']) ?? 'multiFamily',
      nearby,
    };
    const resolvedCopy = resolveFn(
      {
        ...profileCopyRaw,
        // Reuse the guide's assessed-value label/note — same figure semantics.
        statLabel: this.copy.statLabel,
        statNote: this.copy.statNote,
      },
      profileView,
    );
    this.profileView = profileView;
    this.profileCopy = resolvedCopy;
    // Render the @if branch so the anchor exists, then create the preloaded
    // profile component with its inputs (synchronous — works in prerender).
    this.cdr.detectChanges();
    const host = this.profileHost();
    if (!host) {
      return;
    }
    const ref = host.createComponent(ProfileComponent);
    ref.setInput('view', profileView);
    ref.setInput('copy', resolvedCopy);

    const title = profileCopyRaw.titleTemplate.replace('{name}', view.displayName);
    const description = profileCopyRaw.descriptionTemplate
      .replace('{name}', view.displayName)
      .replace('{avgAssessed}', this.formatCad(view.avgAssessedValue));
    this.seo.setPage({
      title,
      description,
      path: `/communities/${view.slug}/`,
    });
    this.meta.updateTag({ name: 'feasly:cost-data-version', content: this.costDataVersion });
    const pagePath = `/communities/${view.slug}/`;
    this.seo.setJsonLdScript('faq', buildFaqPageSchema(resolvedCopy.faqItems));
    this.seo.setJsonLdScript(
      'business',
      buildLocalBusinessSchema(this.seo.getSiteUrl(), `${this.seo.getSiteUrl()}${pagePath}`),
    );
  }

  private buildView(pageData: CommunityPageData): CommunityView | null {
    const agg = pageData.aggregate;
    if (!agg) return null;
    const displayName = toDisplayName(agg.name);
    const range = pageData.range;
    const tierLabels: Record<TierRow['key'], string> = {
      standard: 'Standard',
      premium: 'Premium',
      luxury: 'Luxury',
    };
    // Profile pages have no build ranges (range is null) — tiers stay empty;
    // the profile template never renders them.
    const tiers: TierRow[] = range
      ? (['standard', 'premium', 'luxury'] as const).map((key) => ({
          key,
          label: tierLabels[key],
          ...range.tiers[key],
        }))
      : [];
    return {
      slug: agg.slug,
      name: agg.name,
      displayName,
      count: agg.count,
      avgAssessedValue: agg.avgAssessedValue,
      avgLotSqft: agg.avgLotSqft,
      tiers,
    };
  }
}

/** Branded 404 path for unknown slugs. */
const NOT_FOUND_PATH = '/404';
