/**
 * LLM narrative prompt construction + narrative validation (RENO-07).
 *
 * The cost engine is deterministic math; the LLM only writes the narrative
 * summary around engine outputs — it never produces dollar figures. This
 * module is the boundary between the two:
 *
 * - `buildNarrativePrompt()` assembles the prompt the narrative worker sends
 *   to the LLM. It interpolates ONLY the engine output (figures +
 *   assumptions) and CityFacts. Calibration numbers (CostData / CostParams)
 *   can never reach the prompt: the parameter type makes passing them a
 *   compile error, asserted by narrative.test.ts.
 * - `validateNarrative()` rejects any narrative containing a $-figure that
 *   did not come from the engine output, or missing the verbatim footer.
 *
 * Pure string building: no I/O, no clock, no env (covered by the
 * engine-purity scan).
 */
import type {
  EstimateResult,
  RangedAmount,
  RenoEstimateResult,
} from './types';

/** Which estimate the narrative describes. */
export type NarrativeProjectType = 'new_build' | 'renovation';

/** Union of engine outputs the narrative worker may narrate. */
export type EstimateOutput = EstimateResult | RenoEstimateResult;

/**
 * City facts the prompt may reference. Place facts only (city, community) —
 * never prices. Dollar-free by construction.
 */
export interface CityFacts {
  /** e.g. "Calgary". */
  readonly city: string;
  /** e.g. "Alberta". */
  readonly province: string;
  /** e.g. "Beltline". Optional — omitted when unknown. */
  readonly community?: string;
}

/**
 * The ONLY input `buildNarrativePrompt` accepts. CostData / CostParams is
 * not assignable to this type, so calibration numbers cannot be
 * interpolated into a prompt — a type-level guarantee (AC3).
 */
export interface NarrativePromptInput {
  readonly projectType: NarrativeProjectType;
  readonly estimate: EstimateOutput;
  readonly cityFacts: CityFacts;
}

/** The assembled prompt: system framing + user context. */
export interface NarrativePrompt {
  readonly system: string;
  readonly user: string;
}

/** Matches a $-figure token: "$1,050,000", "$25000", "$99.99". Never swallows trailing commas. */
const FIGURE_PATTERN = /\$\s?\d{1,3}(?:,\d{3})*(?:\.\d+)?/g;

/** Verbatim footer on every generated narrative (pinned by test). */
export const NARRATIVE_FOOTER =
  'Dollar figures are calculated deterministically from our cost model — not generated by AI.';

/** Format a whole-dollar CAD amount: 1050000 -> "$1,050,000". */
function formatCadWhole(dollars: number): string {
  const rounded = Math.round(dollars);
  return '$' + rounded.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

/** Format a closed range the same way everywhere (prompt and validator). */
function formatRange(range: RangedAmount): string {
  return `${formatCadWhole(range.low)} – ${formatCadWhole(range.base)} – ${formatCadWhole(range.high)}`;
}

/**
 * Engine-authored assumptions — the qualitative engine→narrative channel.
 * New-build outputs carry none; reno outputs carry the RENO-01 list.
 */
function assumptionsOf(estimate: EstimateOutput): readonly string[] {
  return 'assumptions' in estimate ? estimate.assumptions : [];
}

/** Labeled figure lines for the user prompt (one line per priced row/total). */
function figureLines(estimate: EstimateOutput): string[] {
  const lines = estimate.rows.map(
    (row) => `- ${row.label}: ${formatRange(row.range)} (low – base – high)`,
  );
  if ('totals' in estimate) {
    lines.push(`- Build total: ${formatRange(estimate.totals.build)} (low – base – high)`);
    lines.push(`- Land (assessed value, fixed): ${formatCadWhole(estimate.totals.land.value)}`);
    lines.push(`- Project total: ${formatRange(estimate.totals.total)} (low – base – high)`);
  } else {
    lines.push(`- Renovation total: ${formatRange(estimate.total)} (low – base – high)`);
  }
  return lines;
}

/**
 * Every $-figure the engine produced, as exact strings. The validator
 * permits exactly these (plus figures quoted inside assumptions).
 */
export function allowedNarrativeFigures(estimate: EstimateOutput): readonly string[] {
  const seen = new Set<string>();
  const add = (figure: string): void => {
    if (!seen.has(figure)) seen.add(figure);
  };
  const addRange = (range: RangedAmount): void => {
    add(formatCadWhole(range.low));
    add(formatCadWhole(range.base));
    add(formatCadWhole(range.high));
  };
  for (const row of estimate.rows) addRange(row.range);
  if ('totals' in estimate) {
    addRange(estimate.totals.build);
    add(formatCadWhole(estimate.totals.land.value));
    addRange(estimate.totals.total);
  } else {
    addRange(estimate.total);
  }
  for (const assumption of assumptionsOf(estimate)) {
    for (const figure of assumption.match(FIGURE_PATTERN) ?? []) {
      add(figure);
    }
  }
  return [...seen];
}

/** Rules every narrative must obey — shared by new-build and reno prompts. */
const SHARED_RULES: readonly string[] = [
  'Never invent a dollar figure. Every $ figure you write must be one of the engine figures provided, copied exactly.',
  'Never state per-square-foot rates, margin percentages, contingency percentages, or any calibration parameter.',
  'Never present figures as quotes, guarantees, or appraisals. They are planning ranges from current cost data.',
  'Never claim what a specific builder will charge.',
  'Write for a homeowner, not a contractor. Be helpful and concrete, never surveillance-toned.',
];

/**
 * Reno-specific banned-list additions (RENO-07, AC1). Each is an explicit
 * "do not" instruction in the reno system prompt, pinned by test.
 */
const RENO_RULES: readonly string[] = [
  'Do not assert structural conditions of the existing home (foundation, framing, soil, drainage) beyond the facts given.',
  'Do not assert that the existing home complies with current building code, or guarantee that permits will be approved.',
  'Do not claim the renovation will increase the home\'s market value by a specific dollar amount.',
  'Speak to renovation realities: existing-condition risk uncovered during demolition, permit timelines, and what it is like to live through construction.',
];

function renderRules(rules: readonly string[]): string {
  return rules.map((rule) => `- ${rule}`).join('\n');
}

function buildSystemPrompt(projectType: NarrativeProjectType, cityFacts: CityFacts): string {
  const place = `${cityFacts.city}, ${cityFacts.province}`;
  const project =
    projectType === 'renovation'
      ? 'a home renovation cost estimate'
      : 'a new home build cost estimate';
  const rules =
    projectType === 'renovation'
      ? [...SHARED_RULES.slice(0, 4), ...RENO_RULES, SHARED_RULES[4]]
      : SHARED_RULES;
  return [
    `You are Feasly's estimate narrator. You write the plain-language summary of ${project} for a homeowner in ${place}.`,
    '',
    'Rules — do not break these:',
    renderRules(rules),
    '',
    `End every narrative with exactly this sentence: "${NARRATIVE_FOOTER}"`,
  ].join('\n');
}

function buildUserPrompt(input: NarrativePromptInput): string {
  const { projectType, estimate, cityFacts } = input;
  const community = cityFacts.community
    ? `${cityFacts.community}, ${cityFacts.city}`
    : cityFacts.city;
  const project =
    projectType === 'renovation' ? 'Home renovation' : 'New home build';
  const lines = [
    `Project: ${project} in ${community}`,
    '',
    'Engine figures — the ONLY dollar figures you may reference:',
    ...figureLines(estimate),
  ];
  const assumptions = assumptionsOf(estimate);
  if (assumptions.length > 0) {
    lines.push('', 'Engine assumptions:', ...assumptions.map((a) => `- ${a}`));
  }
  return lines.join('\n');
}

/**
 * Build the LLM prompt for an estimate narrative. Interpolates ONLY the
 * engine output (figures + assumptions) and CityFacts — never CostData /
 * CostParams (compile-time enforced by the parameter type).
 */
export function buildNarrativePrompt(input: NarrativePromptInput): NarrativePrompt {
  return {
    system: buildSystemPrompt(input.projectType, input.cityFacts),
    user: buildUserPrompt(input),
  };
}

/** Result of validating a generated narrative against the engine output. */
export interface NarrativeValidation {
  readonly ok: boolean;
  /** Human-readable violation descriptions; empty when ok. */
  readonly violations: readonly string[];
}

/**
 * Validate a generated narrative: every $-figure must be one the engine
 * produced, and the verbatim footer must be present.
 */
export function validateNarrative(
  narrative: string,
  estimate: EstimateOutput,
): NarrativeValidation {
  const violations: string[] = [];
  const allowed = new Set(allowedNarrativeFigures(estimate));
  const figures = narrative.match(FIGURE_PATTERN) ?? [];
  for (const figure of figures) {
    if (!allowed.has(figure)) {
      violations.push(`Invented dollar figure not from the engine output: "${figure}"`);
    }
  }
  if (!narrative.includes(NARRATIVE_FOOTER)) {
    violations.push('Missing the verbatim footer: "Dollar figures are calculated deterministically from our cost model — not generated by AI."');
  }
  return { ok: violations.length === 0, violations };
}
