/**
 * Phase-2 wiring — pre-gate preview endpoint tests.
 *
 * Service (deps faked at the interface boundary), route (service stubbed),
 * and contract-conformance: every response parses through the contracts
 * `PreviewEstimateResponse` zod schema. Per the merged contract (2026-09-26)
 * the preview carries the REAL computed figures — build/total ranges and
 * the fixed land value — with rows always empty. The blur is a lead-capture
 * nudge, not a security boundary: figures are readable in the API response
 * by design.
 */
import { describe, expect, it } from 'vitest';
import type {
  ComparisonEstimateResponse,
  EstimateResponse,
} from '@feasly/contracts';
import { ErrorCodes, HttpError } from '../src/middleware/errors';
import { PreviewEstimateResponseSchema } from '../src/openapi/schemas';
import { createPreviewRoute } from '../src/routes/preview.route';
import type { EstimateService } from '../src/services/estimate.service';
import {
  createPreviewService,
  type PreviewService,
} from '../src/services/preview.service';

const FULL_ESTIMATE: EstimateResponse = {
  estimateId: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
  addressKey: 'calgary:123-elm-st',
  inputs: { sqft: 2200, tier: 'standard', garage: 'double', basement: 'unfinished' },
  figures: {
    build: { low: 400000, base: 450000, high: 500000 },
    total: { low: 700000, base: 780000, high: 860000 },
    land: { value: 330000 },
  },
  rows: [
    { key: 'site-prep', label: 'Site prep', range: { low: 10000, base: 12000, high: 14000 } },
  ],
  costDataVersion: 'placeholder-1',
  createdAt: '2026-09-26T05:00:00.000Z',
  disclaimer: 'Dollar figures are calculated deterministically from our cost model — not generated by AI.',
};

function fakeEstimateService(
  behavior: (body: unknown) => Promise<EstimateResponse | ComparisonEstimateResponse>,
): EstimateService {
  return { estimate: behavior };
}

describe('preview service', () => {
  it('returns the real computed figures with rows empty — never the itemized breakdown', async () => {
    const service: PreviewService = createPreviewService({
      estimates: fakeEstimateService(async () => FULL_ESTIMATE),
    });
    const result = await service.preview({ property: {}, scope: {} });
    expect(result.estimateId).toBe(FULL_ESTIMATE.estimateId);
    expect(result.addressKey).toBe(FULL_ESTIMATE.addressKey);
    // Real computed figures pass through: the UI renders them blurred
    // pre-gate (readable in the API response by design, 2026-09-26).
    expect(result.figures).toEqual(FULL_ESTIMATE.figures);
    expect(result.figures.build).toEqual({ low: 400000, base: 450000, high: 500000 });
    expect(result.figures.total).toEqual({ low: 700000, base: 780000, high: 860000 });
    expect(result.figures.land).toEqual({ value: 330000 });
    // Rows stay empty pre-gate — the itemized breakdown is never exposed.
    expect(result.rows).toEqual([]);
    const serialized = JSON.stringify(result);
    for (const real of ['400000', '450000', '500000', '700000', '780000', '860000', '330000']) {
      expect(serialized).toContain(real);
    }
    for (const rowOnly of ['site-prep', 'Site prep', '12000', '14000']) {
      expect(serialized).not.toContain(rowOnly);
    }
  });

  it('propagates validation failures from the estimate service', async () => {
    const service: PreviewService = createPreviewService({
      estimates: fakeEstimateService(async () => {
        throw new HttpError(400, ErrorCodes.VALIDATION_FAILED, 'Invalid input.', false);
      }),
    });
    await expect(service.preview({})).rejects.toMatchObject({ status: 400 });
  });

  it('rejects comparison estimates (preview is a new-build/renovation concept)', async () => {
    const service: PreviewService = createPreviewService({
      estimates: fakeEstimateService(
        async () =>
          ({
            ...FULL_ESTIMATE,
            projectType: 'comparison',
          }) as unknown as ComparisonEstimateResponse,
      ),
    });
    await expect(service.preview({})).rejects.toMatchObject({
      status: 400,
      code: ErrorCodes.VALIDATION_FAILED,
    });
  });
});

describe('preview route', () => {
  it('delegates to the preview service and returns the result untouched', async () => {
    const service = createPreviewService({
      estimates: fakeEstimateService(async () => FULL_ESTIMATE),
    });
    const route = createPreviewRoute({ preview: service });
    const result = await route.handle({ property: {}, scope: {} });
    expect(result.figures.build).toEqual({ low: 400000, base: 450000, high: 500000 });
    expect(result.rows).toEqual([]);
  });
});

describe('preview contract conformance', () => {
  it('the route response validates against the contracts PreviewEstimateResponse schema', async () => {
    const route = createPreviewRoute({
      preview: createPreviewService({
        estimates: fakeEstimateService(async () => FULL_ESTIMATE),
      }),
    });
    const result = await route.handle({ property: {}, scope: {} });
    const parsed = PreviewEstimateResponseSchema.safeParse(
      JSON.parse(JSON.stringify(result)),
    );
    expect(parsed.success).toBe(true);
  });
});
