import { Component, inject, OnInit } from '@angular/core';
import { SeoService } from '../../core/seo/seo.service';
import { SiteFooterComponent } from '../../shared/components/site-footer/site-footer.component';
import { SiteNavComponent } from '../../shared/components/site-nav/site-nav.component';
import { LegalReviewBannerComponent } from '../../shared/components/legal-review-banner/legal-review-banner.component';

/**
 * Terms of Use — full draft content (2026-10-05).
 * Copy status: draft-pending-lawyer — Karan: have this reviewed by counsel
 * before launch. The HRD-05 legal gate blocks production deploys until the
 * lawyer approves this copy and the marker is removed.
 * Legal prose lives here (not in config): it changes by legal review,
 * not by deploy tuning. Allowlisted from the no-hardcode tripwire.
 */
@Component({
  selector: 'app-terms-page',
  standalone: true,
  imports: [SiteFooterComponent, SiteNavComponent, LegalReviewBannerComponent],
  template: `
    <app-site-nav />
    <main class="legal" id="main-content" tabindex="-1">
      <app-legal-review-banner />
      <h1>Terms of Use</h1>
      <p class="updated">Last updated: October 2026</p>

      <h2>1. What Feasly is</h2>
      <p>
        Feasly helps you estimate what it might cost to build a home in Calgary, Alberta. The
        service is <strong>free for homeowners</strong>. We make money from builders, not from you,
        and we never sell your information.
      </p>

      <h2>2. Estimates are ranges, not quotes</h2>
      <p>
        Every figure Feasly shows is a <strong>range-based estimate</strong> produced by our
        deterministic cost model — never a quote, offer, or promise of what your build will cost.
        Actual costs depend on your builder, material choices, site conditions, and market changes,
        and any percentage figures we discuss are illustrative, not guarantees.
      </p>
      <ul>
        <li>
          <strong>Dollar figures are calculated deterministically</strong> from our cost model — they
          are not generated by AI
        </li>
        <li>
          <strong>Written summaries</strong> on your report are drafted by AI for context only
        </li>
        <li>
          Feasly serves <strong>Calgary, Alberta only</strong>; addresses outside Calgary cannot be
          estimated
        </li>
        <li>
          Property data comes from the <strong>City of Calgary's open data</strong> and may be
          incomplete or out of date; we show the data's date wherever we show the data
        </li>
        <li>
          Feasly is <strong>not financial, legal, or construction advice</strong> — confirm every
          number with qualified professionals before you commit money
        </li>
      </ul>

      <h2>3. Your access</h2>
      <p>
        <strong>Homeowners.</strong> No account or password is needed. Your report link is a private
        bearer link valid for 7 days — anyone with the link can open your report, so keep it private
        and don't forward it except through the in-report partner-share feature (which issues a
        separate private link).
      </p>
      <p>
        <strong>Builders and administrators.</strong> You sign in with your organization's
        credentials through Microsoft Entra External ID. You are responsible for activity under your
        account and for keeping your credentials confidential. Builder administrators are responsible
        for the users in their organization.
      </p>

      <h2>4. Acceptable use</h2>
      <p>
        Use Feasly for lawful personal planning. You agree not to: scrape or bulk-copy the service;
        misrepresent an estimate as a builder's quote; submit someone else's personal information
        without their permission; interfere with other users' access; or use the service for any
        unlawful purpose. We may suspend access that violates these terms.
      </p>

      <h2>5. How leads and builder contact work</h2>
      <p>
        When you submit the lead gate, you agree that Feasly and builders associated with us may
        contact you about your estimate. Matched builders can see your name, email, phone number,
        property address, timeline, and lead score for their assigned leads only. You can opt out of
        further contact at any time (Privacy Policy, section 8) — opting out never invalidates a
        report you've already received.
      </p>

      <h2>6. Terms for builders</h2>
      <p>
        These commercial terms apply to builders using the Feasly portal, in addition to everything
        above:
      </p>
      <ul>
        <li>
          <strong>Commission.</strong> A commission calculated as a percentage of the signed
          construction contract value, excluding land, on contracts attributed to Feasly
          introductions. The applicable rate is set out in your builder agreement with us
        </li>
        <li>
          <strong>Attribution.</strong> A contract signed within 365 days of the introduction is
          attributed to Feasly
        </li>
        <li><strong>Reporting.</strong> Report signed contracts within 14 days of signing</li>
        <li>
          <strong>Review and payment.</strong> Each commission invoice opens a 7-day review window.
          Invoices not disputed in that window are finalized and the card on file is charged
          automatically through Stripe. Disputed invoices are never charged while the dispute is
          open
        </li>
        <li>
          <strong>Disputes.</strong> Open a dispute from your portal within the 7-day review window
          with a written reason. Our team resolves disputes; if a charge fails, we retry up to 3
          times before handling it manually
        </li>
        <li>
          <strong>Your obligations.</strong> Keep your organization details, billing contact, and
          card on file current. Only your organization's own leads, invoices, and users are visible
          to you
        </li>
      </ul>
      <p>
        Builder-specific commercial arrangements beyond these terms are set out in your builder
        agreement with us.
      </p>

      <h2>7. Intellectual property</h2>
      <p>
        Feasly, its design, cost model, and content are owned by ____ and protected by intellectual
        property laws. Your estimate inputs and personal information remain yours (see Privacy
        Policy). You grant us a license to use your inputs only to operate and improve the service
        as described in the Privacy Policy.
      </p>

      <h2>8. Disclaimers</h2>
      <p>
        Feasly is provided <strong>"as is"</strong> while in development. We work hard to keep it
        accurate and available, but we do not warrant that it will be error-free, uninterrupted, or
        fit for any particular purpose.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, ____ is not liable for any indirect, incidental,
        consequential, or punitive damages arising from your use of Feasly — including any reliance
        on estimates. Our total liability is limited to the amounts you paid us (homeowners: $0).
      </p>

      <h2>10. Termination</h2>
      <p>
        You may stop using Feasly at any time. We may suspend or terminate access that violates
        these terms or misuses the service.
      </p>

      <h2>11. Governing law</h2>
      <p>
        These terms are governed by the laws of <strong>Alberta, Canada</strong>. Any dispute will
        be resolved in the courts of Alberta.
      </p>

      <h2>12. Changes to these terms</h2>
      <p>
        We may update these terms as Feasly evolves. Material changes will be posted here with a new
        "last updated" date, and continued use of the service after changes take effect constitutes
        acceptance.
      </p>

      <h2>13. Contact</h2>
      <p>Questions about these terms: <strong>____</strong>.</p>
    </main>
    <app-site-footer />
  `,
  styleUrl: './legal.scss',
})
export class TermsPageComponent implements OnInit {
  private readonly seo = inject(SeoService);

  ngOnInit(): void {
    this.seo.setForRoute('terms');
  }
}
