import { Component, inject, OnInit } from '@angular/core';
import { ConfigService } from '../../core/config/config.service';
import { SeoService } from '../../core/seo/seo.service';
import { SiteFooterComponent } from '../../shared/components/site-footer/site-footer.component';
import { SiteNavComponent } from '../../shared/components/site-nav/site-nav.component';

/**
 * Terms of Use (FE1-001 minimal page — M1 plain-language version).
 * Karan: have this reviewed by counsel before launch.
 * Legal prose lives here (not in config): it changes by legal review,
 * not by deploy tuning. Allowlisted from the no-hardcode tripwire.
 */
@Component({
  selector: 'app-terms-page',
  standalone: true,
  imports: [SiteFooterComponent, SiteNavComponent],
  template: `
    <app-site-nav />
    <main class="legal" id="main-content" tabindex="-1">
      <h1>Terms of Use</h1>
      <p class="updated">Last updated: September 2026</p>

      <h2>Estimates are ranges, not guarantees</h2>
      <p>
        Every figure Feasly shows is a range-based estimate produced by our deterministic cost
        model — never a quote, offer, or promise of what your build will cost. Actual costs depend
        on your builder, material choices, site conditions, and market changes. Feasly is not
        financial advice; confirm every number with qualified professionals before you commit.
      </p>

      <h2>AI narrative</h2>
      <p>
        Written summaries on your report are generated by AI for context only. Dollar figures are
        calculated deterministically from our cost model — not generated by AI.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Use Feasly for lawful personal planning. Don't scrape the service, misrepresent estimates
        as quotes from a builder, or interfere with other users' access.
      </p>

      <h2>Availability</h2>
      <p>
        Feasly is provided as-is while in development. Property data comes from the City of Calgary
        and may be incomplete or out of date; we show the data's date wherever we show the data.
      </p>
    </main>
    <app-site-footer />
  `,
  styleUrl: './legal.scss',
})
export class TermsPageComponent implements OnInit {
  private readonly seo = inject(SeoService);
  private readonly config = inject(ConfigService);

  ngOnInit(): void {
    this.seo.setPage({
      title: this.config.get('copy').seo.termsTitle,
      description: this.config.get('copy').seo.terms,
      path: '/terms',
    });
  }
}
